services:
  - type: web
    name: sami-ecom
    runtime: python
    plan: free
    buildCommand: bash build.sh
    startCommand: gunicorn ecom.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.8
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: DB_ENGINE
        value: django.db.backends.mysql
      - key: MYSQL_DATABASE
        sync: false
      - key: MYSQL_USER
        sync: false
      - key: MYSQL_PASSWORD
        sync: false
      - key: MYSQL_HOST
        sync: false
      - key: MYSQL_PORT
        sync: false
      - key: MYSQL_SSL_CA_CONTENT
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
      - key: DJANGO_ALLOWED_HOSTS
        sync: false
      - key: EMAIL_HOST
        sync: false
      - key: EMAIL_PORT
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: DEFAULT_FROM_EMAIL
        sync: false
      - key: SSLCOMMERZ_STORE_ID
        sync: false
      - key: SSLCOMMERZ_STORE_PASSWORD
        sync: false
      - key: SSLCOMMERZ_API_URL
        sync: false
      - key: SSLCOMMERZ_VALIDATION_API
        sync: false
