"""
Django settings for ecom project.
Generated by 'django-admin startproject' using Django 5.2.4.
"""

import os
import tempfile
from pathlib import Path
from dotenv import load_dotenv

BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / ".env")


def env_list(name):
    return [item.strip() for item in os.environ.get(name, "").split(",") if item.strip()]


def mysql_ca_path():
    ca_content = (
        os.environ.get("MYSQL_SSL_CA_CONTENT")
        or os.environ.get("AIVEN_CA_CERT")
        or os.environ.get("AIVEN_CA_CERTIFICATE")
    )
    if ca_content:
        ca_path = Path(tempfile.gettempdir()) / "aiven-mysql-ca.pem"
        ca_path.write_text(ca_content.replace("\\n", "\n"), encoding="utf-8")
        return ca_path

    ca_path = (
        os.environ.get("MYSQL_SSL_CA")
        or os.environ.get("AIVEN_CA_CERT_PATH")
        or os.environ.get("MYSQL_ATTR_SSL_CA")
    )
    if ca_path:
        candidate = Path(ca_path)
        if not candidate.is_absolute():
            candidate = BASE_DIR / candidate
        return candidate

    bundled_ca = BASE_DIR / "ca.pem"
    if bundled_ca.exists():
        return bundled_ca

    return None


# Security

SECRET_KEY = os.environ.get("SECRET_KEY", "django-insecure-local-dev-key")

DEBUG = os.environ.get("DEBUG", "False") == "True"

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "testserver",
    ".onrender.com",
]

RENDER_EXTERNAL_HOSTNAME = os.environ.get("RENDER_EXTERNAL_HOSTNAME")
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

ALLOWED_HOSTS.extend(env_list("DJANGO_ALLOWED_HOSTS"))

CSRF_TRUSTED_ORIGINS = [
    "https://*.onrender.com",
]
CSRF_TRUSTED_ORIGINS.extend(env_list("CSRF_TRUSTED_ORIGINS"))

IS_RENDER = os.environ.get("RENDER") == "true" or bool(RENDER_EXTERNAL_HOSTNAME)

SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True

if IS_RENDER and not DEBUG:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True

LOGIN_URL = "/backend/login/"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",

    "backend",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",

    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


ROOT_URLCONF = "ecom.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",

                "backend.context_processors.menu_items",
                "backend.context_processors.get_cart_item",
                "backend.context_processors.storefront_catalog",
            ],
        },
    },
]

WSGI_APPLICATION = "ecom.wsgi.application"


# Database

DB_ENGINE = os.environ.get("DB_ENGINE", "django.db.backends.mysql")

if DB_ENGINE == "django.db.backends.sqlite3":
    DATABASES = {
        "default": {
            "ENGINE": DB_ENGINE,
            "NAME": os.environ.get("DB_NAME", BASE_DIR / "db.sqlite3"),
        }
    }
else:
    mysql_options = {
        "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
    }
    mysql_ssl_mode = os.environ.get("MYSQL_SSL_MODE", "REQUIRED").upper()
    if mysql_ssl_mode in {"REQUIRED", "VERIFY_CA", "VERIFY_IDENTITY", "DISABLED", "PREFERRED"}:
        mysql_options["ssl_mode"] = mysql_ssl_mode

    mysql_ssl_ca = mysql_ca_path()
    if mysql_ssl_ca and mysql_ssl_mode in {"VERIFY_CA", "VERIFY_IDENTITY"}:
        mysql_options["ssl"] = {
            "ca": str(mysql_ssl_ca),
        }

    DATABASES = {
        "default": {
            "ENGINE": DB_ENGINE,
            "NAME": os.environ.get("MYSQL_DATABASE") or os.environ.get("DB_NAME"),
            "USER": os.environ.get("MYSQL_USER") or os.environ.get("DB_USER"),
            "PASSWORD": os.environ.get("MYSQL_PASSWORD") or os.environ.get("DB_PASSWORD"),
            "HOST": os.environ.get("MYSQL_HOST") or os.environ.get("DB_HOST"),
            "PORT": os.environ.get("MYSQL_PORT") or os.environ.get("DB_PORT"),
            "OPTIONS": mysql_options,
        }
    }


# Password validation

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Media files

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Email configuration

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.environ.get("EMAIL_HOST", "smtp.office365.com")
EMAIL_PORT = int(os.environ.get("EMAIL_PORT", 587))
EMAIL_HOST_USER = os.environ.get("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = os.environ.get("EMAIL_HOST_PASSWORD")
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
DEFAULT_FROM_EMAIL = os.environ.get("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)


# Payment Gateway

SSLCOMMERZ_STORE_ID = os.environ.get("SSLCOMMERZ_STORE_ID")
SSLCOMMERZ_STORE_PASSWORD = os.environ.get("SSLCOMMERZ_STORE_PASSWORD")
SSLCOMMERZ_API_URL = os.environ.get("SSLCOMMERZ_API_URL")
SSLCOMMERZ_VALIDATION_API = os.environ.get("SSLCOMMERZ_VALIDATION_API")
